# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UELogApp', '0003_auto_20170706_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfPath', models.FilePathField(default=None)),
                ('resultPath', models.FilePathField(default=None)),
                ('recordTime', models.DateTimeField(default=None)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
