# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UELogApp', '0009_auto_20170707_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='configXml',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ftpPath',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='hdfsPath',
            field=models.CharField(max_length=255),
        ),
    ]
