# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UELogApp', '0010_auto_20170707_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultrecord',
            name='resultPath',
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='calcStatus',
            field=models.CharField(default='NOT_COMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='hdfsPath',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='parserStatus',
            field=models.CharField(default='NOT_COMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='configXml',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='resultrecord',
            name='isfPath',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='resultrecord',
            name='recordTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
